# Causal Inference Configuration
dtype: "bf16"
text_encoder_path: /mnt/workspace/jdsu/ckpts/Wan-AI/Wan2.1-T2V-1.3B/models_t5_umt5-xxl-enc-bf16.pth
image_encoder_path: None
dit_path: /mnt/workspace/models/livevideo/model.safetensors
vae_path: /mnt/workspace/jdsu/ckpts/Wan-AI/Wan2.1-T2V-1.3B/Wan2.1_VAE.pth
wav2vec_path: /mnt/workspace/jdsu/ckpts/facebook/wav2vec2-base-960h
sp_size: 1

# Data parameters
seed: 42
image_sizes_720: [[400, 720], 
             [720, 720], 
             [720, 400]]
image_sizes_1280: [
             [720, 720], 
             [528, 960],
             [960, 528],
             [720, 1280],
             [1280, 720]]
max_hw: 720 # 720: 480p; 1280: 720p
guidance_scale: 4.5
audio_scale: 
num_steps: 4
fps: 16
sample_rate: 16000
negative_prompt: "Vivid color tones, background/camera moving quickly, screen switching, subtitles and special effects, mutation, overexposed, static, blurred details, subtitles, style, work, painting, image, still, overall grayish, worst quality, low quality, JPEG compression residue, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn face, deformed, disfigured, malformed limbs, fingers merging, motionless image, chaotic background, three legs, crowded background with many people, walking backward"
use_fsdp: False
tea_cache_l1_thresh: 0 # 0.14 The larger this value is, the faster the speed, but the worse the visual quality.

# Causal inference specific parameters
denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true
num_transformer_blocks: 30
frame_seq_length: 1125
num_frame_per_block: 3
independent_first_frame: False
use_audio: True

model_config:
  local_attn_size: 30  # Enable KV cache eviction for 30 frames of history
  sink_size: 0         # Number of initial frames to keep permanently in cache
